// <auto-generated />
using System;
using CarStore.Infrastructure.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarStore.Infrastructure.DB.Migrations
{
    [DbContext(typeof(CarStoreDbContext))]
    partial class CarStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("CarStore.Domain.Models.Cars.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mark")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarStore.Domain.Models.Primitives.DomainEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("DomainEvent");
                });

            modelBuilder.Entity("CarStore.Domain.Models.Cars.Car", b =>
                {
                    b.OwnsOne("CarStore.Domain.Models.ValueObjects.Money", "InitialPrice", b1 =>
                        {
                            b1.Property<Guid>("CarId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Amount")
                                .HasColumnType("REAL");

                            b1.Property<int>("Currency")
                                .HasColumnType("INTEGER");

                            b1.HasKey("CarId");

                            b1.ToTable("Cars");

                            b1.WithOwner()
                                .HasForeignKey("CarId");
                        });

                    b.Navigation("InitialPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStore.Domain.Models.Primitives.DomainEvent", b =>
                {
                    b.HasOne("CarStore.Domain.Models.Cars.Car", null)
                        .WithMany("Events")
                        .HasForeignKey("CarId");
                });

            modelBuilder.Entity("CarStore.Domain.Models.Cars.Car", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
